version: "3.7"
services:
  bootstrap:
    image: &image nutsfoundation/nuts-node:latest
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
      NUTS_NETWORK_PUBLICADDR: bootstrap:5555
    ports:
      - 8080:8080
    healthcheck:
      test: "curl -f http://localhost:8080/status || exit 1"
    volumes:
      - "./nuts.yaml:/opt/nuts/nuts.yaml"
      - "./truststore.pem:/opt/nuts/truststore.pem"
      - "./bootstrap/certificate.pem:/opt/nuts/certificate.pem"
  node1:
    image: *image
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    healthcheck:
      test: "curl -f http://localhost:8080/status || exit 1"
    volumes:
      - "./nuts.yaml:/opt/nuts/nuts.yaml"
      - "./truststore.pem:/opt/nuts/truststore.pem"
      - "./node1/certificate.pem:/opt/nuts/certificate.pem"
  node2:
    image: *image
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    healthcheck:
      test: "curl -f http://localhost:8080/status || exit 1"
    volumes:
      - "./nuts.yaml:/opt/nuts/nuts.yaml"
      - "./truststore.pem:/opt/nuts/truststore.pem"
      - "./node2/certificate.pem:/opt/nuts/certificate.pem"
