openapi: "3.0.0"
info:
  title: Nuts Verifiable Credential API spec
  description: |
    API specification for common operations on Verifiable credentials.
    It allows the three roles, issuer, holer and verifier to issue, revoke, search, present and verify credentials.
  version: 2.0.0
  license:
    name: GPLv3
servers:
  - url: http://localhost:1323
paths:
  /internal/vcr/v2/issuer/vc:
    post:
      summary: Issues a new Verifiable Credential
      description: |
        Issues a new Verifiable Credential for provided type in the context.
        
        error returns:
        * 400 - One or more of the given parameters are invalid
        * 500 - An error occurred while processing the request
      operationId: "issueVC"
      tags:
        - credential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueVCRequest'
      responses:
        "200":
          description: "New VC has been created successfully. Returns the Verifiable Credential."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifiableCredential'
        default:
          $ref: '../common/error_response.yaml'

  /internal/vcr/v2/issuer/vc/search:
    get:
      summary: "Searches for verifiable credentials issued by this node which matches the search params"
      description: >
        The SearchVCResult contains a list of matching credentials regardless of the validity.
        The entry may contain a revocation which means the credential has been revoked.

        error returns:
        * 404 - Corresponding credential could not be found
        * 500 - An error occurred while processing the request
      operationId: "searchIssuedVCs"
      parameters:
        - name: credentialType
          in: query
          description: The type of the credential
          example: NutsOrganizationCredential
          required: true
          schema:
            type: string
        - name: issuer
          in: query
          description: the DID of the issuer
          example: did:nuts:123
          required: true
          schema:
            type: string
        - name: subject
          in: query
          description: the URI which indicates the subject (usually a DID)
          example: did:nuts:456
          required: false
          schema:
            type: string
      tags:
        - credential
      responses:
        "200":
          description: A list of matching credentials
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/SearchVCResult'
        default:
          $ref: '../common/error_response.yaml'
  /internal/vcr/v2/issuer/vc/{id}:
    parameters:
      - name: id
        in: path
        description: URL encoded ID.
        required: true
        example: "did:nuts:B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY#c4199b74-0c0a-4e09-a463-6927553e65f5"
        schema:
          type: string
    delete:
      summary: "Revoke an issued credential"
      description: |
        Revoke a credential.

        error returns:
        * 400 - Credential can't be revoked. Most likely due to a missing private key.
        * 404 - Credential is not found
        * 409 - Credential has already been revoked
        * 500 - An error occurred while processing the request
      operationId: "revokeVC"
      tags:
        - credential
      responses:
        "200":
          description: Revocation has been processed locally. It has also been published to the network.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Revocation'
        default:
          $ref: '../common/error_response.yaml'
  /internal/vcr/v2/verifier/vc:
    post:
      summary: Verifies a Verifiable Credential
      description: |
        Verifies a Verifiable Credential. It checks: 
        * The signature
        * Expiration
        * Rrevocation status
        * If the issuer is trusted
        * If the issuer was not deactivated at time of issuing
        
        error returns:
        * 400 - One or more of the given parameters are invalid
        * 500 - An error occurred while processing the request
      operationId: "verifyVC"
      tags:
        - credential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VCVerificationRequest'
      responses:
        "200":
          description: "The verification result"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VCVerificationResult'
        default:
          $ref: '../common/error_response.yaml'

  /internal/vcr/v2/holder/vp:
    post:
      summary: Create a new Verifiable Presentation for a set of Verifiable Credentials.
      description: |
        Given a list of VCs, create a new presentation.

        error returns:
        * 400 - Invalid paramters
        * 500 - An error occurred while processing the request
      operationId: createVP
      tags:
        - credential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateVPRequest"
      responses:
        "200":
          description: The verifiable presentation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifiablePresentation"


components:
  schemas:
    IssueVCRequest:
      type: object
      description: A request for issuing a new Verifiable Credential.
      required:
        - type
        - issuer
        - credentialSubject
      properties:
        "@context":
          description: |
            The resolvable context of the credentialSubject as URI. If omitted, the "https://nuts.nl/credentials/v1" context is used.
            Note: it is not needed to provide the "https://www.w3.org/2018/credentials/v1" context here.
          type: string
          example: "http://schema.org"
          default: "https://nuts.nl/credentials/v1"
        type:
          description: Type definition for the credential.
          type: string
          example: "NutsOrganizationCredential"
        issuer:
          description: DID according to Nuts specification.
          type: string
          example: "did:nuts:B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY"
        expirationDate:
          description: rfc3339 time string until when the credential is valid.
          type: string
          example: "2012-01-02T12:00:00Z"
        publishToNetwork:
          description: |
            If set, the node publishes this credential to the network. This is the default behaviour.
            When set to false, the caller is responsible for distributing the VC to a holder. When the issuer is
            also the holder, it then can be used to directly create a presentation (self issued).
            Note: a not published credential can still be publicaly revoked.
          type: boolean
          default: true
        visibility:
            description: |
              When publishToNetwork is true, the credential can be published publicly of privately to the holder.
              This field is mandatory if publishToNetwork is true to prevent accidents.
            type: string
            enum: [ public, private ]
            default: private
        credentialSubject:
          $ref: '#/components/schemas/CredentialSubject'
    VerifiableCredential:
      type: object
      description: A credential according to the W3C and Nuts specs.
      required:
        - "@context"
        - type
        - issuer
        - issuanceDate
        - credentialSubject
        - proof
      properties:
        "@context":
          description: "List of URIs of JSON-LD contexts of the VC."
          type: array
          items:
            type: string
        id:
          description: Credential ID. An URI wich uniquely identifies the credential e.g. the issuers DID concatenated with an uuid.
          example: "did:nuts:123#B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY"
          type: string
        type:
          description: List of type definitions for the credential.
          type: array
          items:
            type: string
        issuer:
          $ref: '#/components/schemas/DID'
        issuanceDate:
          description: rfc3339 time string when the credential was issued.
          type: string
          example: "2012-01-02T12:00:00Z"
        expirationDate:
          description: rfc3339 time string untill when the credential is valid.
          type: string
          example: "2012-01-02T12:00:00Z"
        credentialSubject:
          $ref: '#/components/schemas/CredentialSubject'
        proof:
          description: one or multiple cryptographic proofs
          type: object
    SearchVCResult:
      type: object
      description: result of a Resolve operation.
      required:
        - verifiableCredential
      properties:
        revocation:
          $ref: "#/components/schemas/Revocation"
        verifiableCredential:
          $ref: "#/components/schemas/VerifiableCredential"
    Revocation:
      type: object
      description: Credential revocation record
      required:
        - issuer
        - subject
        - date
      properties:
        issuer:
          $ref: '#/components/schemas/DID'
        subject:
          type: string
          description: subject refers to the credential identifier that is revoked (not the credential subject)
        reason:
          type: string
          description: reason describes why the VC has been revoked
        date:
          type: string
          description: date is a rfc3339 formatted datetime.
        proof:
          type: object
          description: Proof contains the cryptographic proof(s).
    DID:
      type: string
      description: DID according to Nuts specification
      example: "did:nuts:B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY"
    CredentialSubject:
      type: object
      description: Subject of a Verifiable Credential identifying the holder and expressing claims.

    VCVerificationRequest:
      required:
        - verifiableCredential
      properties:
        verifiableCredential:
          $ref: "#/components/schemas/VerifiableCredential"
        verificationOptions:
          $ref: "#/components/schemas/VCVerificationOptions"
    VCVerificationOptions:
      type: object
      properties:
        allowUntrustedIssuer:
          description: If set to true, an untrusted credential issuer is alowed.
          type: boolean
          default: false
    VCVerificationResult:
      description: Contains the verifiable credential verification result.
      type: object
      required:
        - validity
      properties:
        validity:
          type: boolean
          description: Indicates the validity of the signature, issuer and revocation state.
        message:
          type: string
          description: Indicates what went wrong

    CreateVPRequest:
      type: object
      description: A request for creating a new Verifiable Presentation for a set of Verifiable Credentials.
      required:
        - verifiableCredentials
      properties:
        verifiableCredentials:
          type: array
          items:
            $ref: "#/components/schemas/VerifiableCredential"
        signerDID:
          description: |
            Specifies the DID of the signing party that must be used to create the digital signature.
            If not specified, it is derived from the given Verifiable Credentials' subjectCredential ID.
            It can only be derived if all given Verifiable Credentials have the same, single subjectCredential.
          type: string
          format: uri
        proofPurpose:
          type: string
          description: |
            The specific intent for the proof, the reason why an entity created it. Acts as a safeguard to prevent the
            proof from being misused for a purpose other than the one it was intended for.
        challenge:
          type: string
          description: |
            A random or pseudo-random value used by some authentication protocols to mitigate replay attacks.
        domain:
          type: string
          description: |
            A string value that specifies the operational domain of a digital proof. This could be an Internet domain
            name like example.com, an ad-hoc value such as mycorp-level3-access, or a very specific transaction value
            like 8zF6T$mqP. A signer could include a domain in its digital proof to restrict its use to particular
            target, identified by the specified domain.
        expires:
          type: string
          description: Date and time at which proof will expire. If omitted, the proof does not have an end date.
          format: date-time
          example: '2021-12-20T09:00:00Z'

    VerifiablePresentation:
      type: object
      description: Verifiable Presentation
      title: Verifiable Presentation Model
      required:
        - "@context"
        - type
      properties:
        "@context":
          description: |
            An ordered set where the first item is a URI https://www.w3.org/2018/credentials/v1. It is used to define
            terms and help to express specific identifiers in a compact manner.
          uniqueItems: true
          example: [
              "https://www.w3.org/2018/credentials/v1"
          ]
          type: array
          items:
            type: string
        id:
          type: string
          description: URI that is used to unambiguously refer to an object, such as a person, product, or organization.
          example: https://example.edu/credentials/1872,
          format: uri
        type:
          description: Type of the object or the datatype of the typed value.
          example:
            - "VerifiableCredential"
            - "UniversityDegreeCredential"
          type: array
          items:
            type: string
        verifiableCredential:
          description: |
            VerifiableCredential is composed of a list containing one or more verifiable credentials, in a
            cryptographically verifiable format.
          type: array
          items:
            $ref: '#/components/schemas/VerifiableCredential'
        holder:
          type: string
          description: "URI of the entity that is generating the presentation."
          format: uri
          example: "did:nuts:123"
        proof:
          $ref: "#/components/schemas/EmbeddedProof"
    EmbeddedProof:
      title: Embedded Proof
      type: object
      description: |
        Cryptographic proofs that can be used to detect tampering and verify the authorship of a
        credential or presentation. An embedded proof is a mechanism where the proof is included in
        the data, such as a Linked Data Signature.
      required:
        - type
        - created
        - proofPurpose
        - verificationMethod
        - jws
      properties:
        type:
          type: string
          description: Type of the object or the datatype of the typed value. Currently only supported value is "JsonWebSignature2020".
          example: JsonWebSignature2020.
        created:
          type: string
          description: Date and time at which proof has been created.
          format: date-time
          example: '2021-12-20T09:00:00Z'
        proofPurpose:
          type: string
          description: |
            It expresses the purpose of the proof and ensures the information is protected by the
            signature.
          example: assertionMethod
        challenge:
          type: string
          description: |
            A random or pseudo-random value, provided by the verifier, used by some authentication protocols to
            mitigate replay attacks.
        domain:
          type: string
          description: |
            A string value that specifies the operational domain of a digital proof. This could be an Internet domain
            name like example.com, an ad-hoc value such as mycorp-level3-access, or a very specific transaction value
            like 8zF6T$mqP. A signer could include a domain in its digital proof to restrict its use to particular
            target, identified by the specified domain.
        nonce:
          type: string
          description: |
            A unique string value generated by the holder, MUST only be used once for a particular domain
            and window of time. This value can be used to mitigate replay attacks.
        verificationMethod:
          type: string
          description: |
            Specifies the public key that can be used to verify the digital signature.
            Dereferencing a public key URL reveals information about the controller of the key,
            which can be checked against the issuer of the credential.
          example: did:nuts:123#key-5
        jws:
          type: string
          description: JSON Web Signature
          example: eyJhbGciOiJFUzI1NksifQ.eyJzdWIiOiJFQlNJIDIwMTkifQ.oggE3ft3kJYPGGa9eBibpbjgeJXw4fLbVMouVoM2NfcDxsl_UUUIarsS1VpBoYEs7s9cBlc4uC0EbnJCHfVJIw