openapi: "3.0.0"
info:
  title: Nuts Verifiable Credential API spec
  description: API specification for Verifiable Credentials
  version: 1.0.0
  license:
    name: GPLv3
paths:
  /internal/credential/v1/vc:
    post:
      summary: Creates a new Veryfiable Credential
      operationId: "create"
      tags:
        - credential
      responses:
        "200":
          description: "New DID has been created successfully. Returns the DID Document."
          content:
            application/vc+json:
              schema:
                $ref: '#/components/schemas/VerifiableCredential'
        "400":
          description: One or more of the given parameters are invalid
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: An error occurred while processing the request.
          content:
            text/plain:
              schema:
                type: string
  /internal/credential/v1/vc/{id}:
    parameters:
      - name: id
        in: path
        description: URL encoded ID.
        required: true
        example:
          - "did:nuts:B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY#90382475609238467"
        schema:
          type: string
    get:
      summary: "Resolves a verifiable credential"
      operationId: "resolve"
      tags:
        - credential
      responses:
        "200":
          description: Credential has been found and is returned.
          content:
            application/vc+json:
              schema:
                $ref: '#/components/schemas/VerifiableCredential'
        "404":
          description: Corresponding credential could not be found.
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: An error occurred while processing the request.
          content:
            text/plain:
              schema:
                type: string
  /internal/credential/v1/revoke/{id}:
    parameters:
      - name: id
        in: path
        description: URL encoded ID.
        required: true
        example:
          - "did:nuts:B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY#90382475609238467"
        schema:
          type: string
    post:
      summary: "Revoke a credential"
      operationId: "revoke"
      tags:
        - credential
      responses:
        "202":
          description: Revocation has been accepted.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerificationOutcome"
        "400":
          description: Credential can't be revoked. Most likely due to a missing private key.
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: Credential is not found.
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: An error occurred while processing the request.
          content:
            text/plain:
              schema:
                type: string
  /internal/credential/v1/{concept}:
    post:
      summary: Search for a concept. A concept is backed by 1 or more VCs
      operationId: "search"
      tags:
        - credential
      requestBody:
        required: true
        description: a query with key value pairs and pagination
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      parameters:
        - name: concept
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Found 0 or more results.
          content:
            application/json:
              example:
              schema:
                type: array
                items:
                  description: the returned JSON depends on the requested concept.
                  type: object
        "400":
          description: invalid params.
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: concept not found.
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: An error occurred while processing the request.
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    CredentialSubject:
      type: object
      description: Contents of a Verifiable Credential giving name and DID of organization.
    KeyValuePair:
      type: object
      description: used search params
      required:
        - key
        - value
      properties:
        key:
          description: >
            Fields from VCs to search on. Concept specific keys must be prepended with the concept name and a '.'.
            Default fields: issuer, subject, type
          type: string
          example: company.name
        value:
          type: string
    SearchRequest:
      type: object
      description: >
        Input for a search call. Parameters are entered as key/value pairs.
        Concept specific query params need to be prepended with the concept name.
      required:
        - params
      properties:
        params:
          description: key/value pairs
          type: array
          items:
            $ref: '#/components/schemas/KeyValuePair'
        offset:
          description: skips first x results, default 0
          type: number
        limit:
          description: limit number of return values to x, default 10
          type: number
    VerifiableCredential:
      type: object
      description: A credential according to the W3C spec.
      required:
        - context
        - type
        - issuer
        - issuanceDate
        - credentialSubject
        - proof
      properties:
        context:
          description: List of URIs
          type: array
          items:
            type: string
        id:
          description: credential ID. A Nuts DID followed by a large number.
          example: "did:nuts:B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY"
          type: string
        type:
          description: List of type definitions for the credential. Always includes 'VerifiableCredential'
          type: array
          items:
            type: string
        issuer:
          description: DID according to Nuts specification
          example: "did:nuts:B8PUHs2AUHbFF1xLLK4eZjgErEcMXHxs68FteY7NDtCY"
          type: string
        issuanceDate:
          description: rfc3339 time string when the credential was issued.
          type: string
          example: "2012-01-02T12:00:00Z"
        expirationDate:
          description: rfc3339 time string untill when the credential is valid.
          type: string
          example: "2012-01-02T12:00:00Z"
        credentialSubject:
          $ref: '#/components/schemas/CredentialSubject'
        proof:
          description: one or multiple cryptographic proofs
          type: object
    VerificationOutcome:
      required:
        - status
      properties:
        status:
          description: if the credential is valid, revoked, untrusted or has some other status.
          type: boolean
        statusReason:
          description: if the credential is not valid, the reason is given here.
          type: string
