version: "2"
checks:
  # Go returns 'error's rather than throwing exceptions, so the safer the code the more errors are returned.
  # To avoid deeply nested if-statements we generally use guard clauses as recommended by Martin Fowler.
  # Guard statements are if-statements that, as early as possible, check conditions and return if failed. They improve readability
  # over nested if-statements. This however leads to many return statements which can't be avoided, so we'll disable the max. exit points check.
  return-statements:
    enabled: false
exclude_patterns:
  - "**/generated.go"
  - "**/test/**/*.go"
  - "**/test.go"
  - "**/*_test.go"
  - "**/test*.go"
  - "**/mock/**/*.go"
  - "**/mock.go"
  - "**/*_mock.go"
  - "docs/**/*.go"
  - "codegen/**/*.go"
  - "**/*.pb.go"
  - "e2e-tests/**/*.go"
plugins:
  gofmt:
    enabled: true
  # golint doesn't support Go 1.19, so it crashes on generics (2022-11-28)
  golint:
    enabled: false
  govet:
    enabled: true