ignore:
  - "**/generated.go"
  - "**/test/"
  - "/test/"
  - "**/test.go"
  - "**/*_test.go"
  - "mock/**/*.go"
  - "**/mock.go"
  - "docs/**/*.go"
  - "**/*.pb.go"
  # Until network protocol implementation has been spec and optionally replace, ignore those sources
  - "network/p2p/"
  - "network/proto/"
github_checks:
  annotations: false
