ignore:
  - "**/generated.go"
  - "**/test/"
  - "/test/"
  - "**/test.go"
  - "**/*_test.go"
  - "mock/**/*.go"
  - "**/mock.go"
  - "**/*_mock.go"
  - "docs/**/*.go"
  - "network/transport/*.go" # generated sources
  - "**/*.pb.go"
  - "**/bindata.go"
  - "**/bindata/**.go"
github_checks:
  annotations: false
