FROM golang:1.15 as builder

LABEL maintainer="info@reinkrul.nl"

ENV GO111MODULE on
ENV GOPATH /

RUN mkdir /opt/nuts && cd /opt/nuts
COPY go.mod .
COPY go.sum .
RUN go mod download && go mod verify

COPY . .
RUN GOOS=linux GOARCH=arm go build -ldflags="-w -s" -o /opt/nuts/nuts

FROM arm32v7/ubuntu:latest
COPY --from=builder /opt/nuts/nuts /usr/bin/nuts

# Make sure CA bundle is up-to-date
RUN apt update && apt install -y ca-certificates

HEALTHCHECK --start-period=30s --timeout=5s --interval=10s \
    CMD curl -f http://localhost:1323/status || exit 1

EXPOSE 1323 4222 5555
ENTRYPOINT ["/usr/bin/nuts"]
CMD ["server"]