FROM nutsfoundation/nuts-node:master as nutsnode
FROM ngrok/ngrok:3-alpine as ngrok

COPY --from=nutsnode /usr/bin/nuts /usr/bin/nuts
COPY --from=ngrok /usr/bin/nuts /usr/bin/nuts


HEALTHCHECK --start-period=30s --timeout=5s --interval=10s \
    CMD curl -f http://localhost:1323/status || exit 1

EXPOSE 1323 5555
ENTRYPOINT ["/usr/bin/nuts"]
CMD ["server"]
