datadir: /opt/nuts/data
strictmode: false
http:
  default:
    address: :1323
    cors:
      origin: "*"
verbosity: debug
auth:
  publicurl: http://node:1323
  contractvalidators:
    - selfsigned
network:
  enabletls: false
