services:
  nodeA:
    image: "${IMAGE_NODE_A:-nutsfoundation/nuts-node:master}"
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    ports:
      - "18081:8081"
    volumes:
      - "./node-A/nuts.yaml:/opt/nuts/nuts.yaml:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often
  nodeB:
    image: "${IMAGE_NODE_B:-nutsfoundation/nuts-node:master}"
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    ports:
      - "28081:8081"
    volumes:
      - "./node-B/nuts.yaml:/opt/nuts/nuts.yaml:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often
