version: "3.7"
services:
  nodeA:
    image: "${IMAGE_NODE_A:-nutsfoundation/nuts-node:master}"
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
      NUTS_NETWORK_NODEDID: "${NODE_A_DID}"
    ports:
      - "18081:8081"
    volumes:
      - "./node-A/data:/opt/nuts/data"
      - "./node-A/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "../../tls-certs/nodeA-certificate.pem:/opt/nuts/certificate-and-key.pem:ro"
      - "../../tls-certs/truststore.pem:/opt/nuts/truststore.pem:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often
  nodeB:
    image: "${IMAGE_NODE_B:-nutsfoundation/nuts-node:master}"
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
      NUTS_NETWORK_NODEDID: "${NODE_B_DID}"
      NUTS_NETWORK_BOOTSTRAPNODES: ${BOOTSTRAP_NODES}
    ports:
      - "28081:8081"
    volumes:
      - "./node-B/data:/opt/nuts/data"
      - "./node-B/nuts.yaml:/opt/nuts/nuts.yaml:ro"
      - "../../tls-certs/nodeB-certificate.pem:/opt/nuts/certificate-and-key.pem:ro"
      - "../../tls-certs/truststore.pem:/opt/nuts/truststore.pem:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often