openapi: "3.0.0"
info:
  title: Nuts DID Manager API spec
  description: API specification for high-level DID management
  version: 0.1.0
  license:
    name: GPLv3
paths:
  /internal/didman/v1/svctpl/{name}:
    parameters:
      - name: name
        in: path
        description: Name of the service template
        required: true
        schema:
          type: string
    post:
      summary: "Applies a service template for a DID"
      operationId: "applyServiceTemplate"
      tags:
        - serviceTemplates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceTemplateRequest"
      responses:
        "204":
          description: "Service template applied"
        "400":
          description: "Invalid subject/controller DID, template name or parameters"
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: "Unapply a service template for a DID"
      operationId: "unapplyServiceTemplate"
      tags:
        - serviceTemplates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceTemplateRequest"
      responses:
        "204":
          description: "Service template unapplied"
        "400":
          description: "Invalid DID or template name"
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    ServiceTemplateRequest:
      type: object
      description: Request for applying/unapplying a service template.
      required:
        - controller
        - subject
      properties:
        controller:
          description: DID of the controller which the service template should be applied to. Can be equal to subject.
          type: string
        subject:
          description: DID of the subject which the service template should be applied to. Can be equal to controller.
          type: string
        params:
          description: Key-value parameters for the service template when applying.
          type: object