openapi: "3.0.0"
info:
  title: Nuts DID Manager API spec
  description: API specification for high-level DID management
  version: 0.1.0
  license:
    name: GPLv3
paths:
  /internal/didman/v1/{did}/svctpl/{name}:
    parameters:
      - name: did
        in: path
        description: DID to operate on
        required: true
        schema:
          type: string
      - name: name
        in: path
        description: Name of the service template
        required: true
        schema:
          type: string
    post:
      summary: "Applies a service template for a DID"
      operationId: "applyServiceTemplate"
      tags:
        - serviceTemplates
      requestBody:
        description: "Map containing template specific parameters"
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          description: "Service template applied"
        "400":
          description: "Invalid DID or template name"
          content:
            text/plain:
              schema:
                type: string
        "406":
          description: "Template parameters are invalid"
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: "Unapplies a service template for a DID"
      operationId: "unapplyServiceTemplate"
      tags:
        - bolts
      responses:
        "204":
          description: "Service template unapplied"
        "400":
          description: "Invalid DID or template name"
          content:
            text/plain:
              schema:
                type: string