openapi: "3.0.0"
info:
  title: Nuts DID Manager API spec
  description: API specification for DID management helper APIs. The goal of this API is to help administrative interfaces to manage DIDs.
  version: 1.0.0
  license:
    name: GPLv3
paths:
  /internal/didman/v1/did/{did}/contactinfo:
    parameters:
      - name: did
        in: path
        description: URL encoded DID.
        required: true
        example:
          - "did:nuts:1234"
        schema:
          type: string
    get:
      operationId: getContactInformation
      responses:
        "200":
          description: The actual Contact Information of the DID document.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactInformation'
        default:
          $ref: '../common/error_response.yaml'
    put:
      summary: Add a predetermined DID Service with real life contact information
      description: |
        In case of emergency or support questions a service provider operating a nuts node should
        provide contact inforamtion such as an emergency phone number and support email address.

        There is at most one contact-information service per DID.
      operationId: updateContactInformation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactInformation'
      responses:
        "200":
          description: The given type and URL have been added as service to the DID Document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactInformation'
        default:
          $ref: '../common/error_response.yaml'
  /internal/didman/v1/did/{did}/endpoint:
    parameters:
      - name: did
        in: path
        description: URL encoded DID.
        required: true
        example:
          - "did:nuts:1234"
        schema:
          type: string
    post:
      operationId: "addEndpoint"
      summary: Add a service endpoint or a reference to a service.
      description: |
        To distinguish from compound services, this type of service will be called an endpoint.
        In the Nuts specs this type of service is called a concrete service.

        Add an endpoint with a type and URL to a DID Service in a Document. The API will convert it to a DID service with the serviceEndpoint set to a URL.
        This API will also check if an endpoint with the same type already exists. This API is not meant to add compound services.

        The URL can either be an Endpoint or a reference to another service.

        error returns:
        * 400 - incorrect input
        * 404 - unknown DID
        * 409 - a service with the same type already exists
      tags:
        - DID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointProperties'
      responses:
        "200":
          description: The service which has been added to the DID Document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Endpoint'
        default:
          $ref: '../common/error_response.yaml'
  /internal/didman/v1/did/{did}/endpoint/{type}:
    parameters:
      - name: did
        in: path
        description: URL encoded DID.
        required: true
        example:
          - "did:nuts:1234"
        schema:
          type: string
      - name: type
        in: path
        description: Type of the service
        required: true
        example:
          - "eOverdracht"
        schema:
          type: string
    delete:
      operationId: deleteEndpointsByType
      description: |
        Delete all endpoints with the provided type from the DID Document.

        error returns:
        * 400 - malformatted input, like the DID or the endpoint type.
        * 404 - DID or service with this type not found.
        * 409 - the service is referenced by other services
      responses:
        204:
          description: |
            All existing endpoints with with this type were succesfully deleted.
        default:
          $ref: '../common/error_response.yaml'
  /internal/didman/v1/did/{did}/compoundservice:
    parameters:
      - name: did
        in: path
        description: URL encoded DID.
        required: true
        example:
          - "did:nuts:1234"
        schema:
          type: string
    get:
      operationId: getCompoundServices
      summary: |
        Get a list of compound services for a DID document.

        error responses:
        * 400 - incorrect input
        * 404 - unknown DID
      responses:
        "200":
          description: |
            The list of compound services on the DID document.
            It excludes special compound services like ContactInformation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompoundService'
        default:
          $ref: '../common/error_response.yaml'
    post:
      summary: Add a compound service to a DID Document.
      description: |
        Add a service to a DID Document that references one or more endpoints using a map. The keys of the map indicate the service name/type, the values contain the references to the endpoints.
        The endpoints may be in the same or in another DID Document, but they must be resolvable when the service is created.
        The references must follow the format for service references as specified by Nuts RFC006.

        This API will also check if an endpoint with the same type already exists. This API is not meant to add endpoints.

        error returns:
        * 400 - incorrect input
        * 404 - unknown DID
        * 409 - a service with the same type already exists
      operationId: "addCompoundService"
      tags:
        - DID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompoundServiceProperties'
      responses:
        "200":
          description: The compound service has been added to the DID Document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompoundService'
        default:
          $ref: '../common/error_response.yaml'
  /internal/didman/v1/service/{id}:
    parameters:
      - name: id
        in: path
        description: URL encoded service ID.
        required: true
        example:
          - "did:nuts:1234#service-x"
        schema:
          type: string
    delete:
      summary: Remove a service from a DID Document.
      description: |
        Remove a service from a DID Document.

        error returns:
        * 400 - incorrect input
        * 404 - unknown DID
        * 409 - the service is referenced by other services
      operationId: "deleteService"
      responses:
        "204":
          description: The service has been removed
        default:
          $ref: '../common/error_response.yaml'
components:
  schemas:
    Endpoint:
      type: object
      description: A combination of type and URL.
      required:
        - id
        - type
        - endpoint
      properties:
        id:
          type: string
        type:
          description: type of the endpoint. May be freely choosen.
          type: string
        endpoint:
          description: An endpoint URL or a reference to another service.
          type: string
          example:
            - ref:did:nuts:123/serviceEndpoint?type=eOverdracht-fhir
            - https://api.example.org/fhir
    EndpointProperties:
      type: object
      description: A combination of type and URL.
      required:
        - type
        - endpoint
      properties:
        type:
          description: type of the endpoint. May be freely choosen.
          type: string
        endpoint:
          description: An endpoint URL or a reference to another service.
          type: string
          example:
            - ref:did:nuts:123/serviceEndpoint?type=eOverdracht-fhir
            - https://api.example.org/fhir
    CompoundServiceProperties:
      type: object
      description: A creation request for a compound service that references endpoints.
      required:
        - type
        - serviceEndpoint
      properties:
        type:
          description: type of the endpoint. May be freely choosen.
          type: string
        serviceEndpoint:
          description: A map containing service references.
          example: {'auth': 'did:nuts:1312321?type=auth'}
          type: object
    CompoundService:
      type: object
      description: A creation request for a compound service that references endpoints.
      required:
        - id
        - type
        - serviceEndpoint
      properties:
        id:
          type: string
        type:
          description: type of the endpoint. May be freely choosen.
          type: string
        serviceEndpoint:
          description: A map containing service references.
          example: {'auth': 'did:nuts:1312321?type=auth'}
          type: object
    ContactInformation:
      type: object
      description: A set of contact information entries
      required:
        - name
        - phone
        - email
        - website
      properties:
        name:
          type: string
          description: The commonly known name of the service provider
        phone:
          type: string
          description: phoneNumber for high priority support
        email:
          type: string
          description: email address for normal priority support
        website:
          type: string
          description: URL of the public website of this Service Provider. Can point to a Nuts specific page with more information about the node and how to contact.
