openapi: "3.0.0"
info:
  title: Nuts network API spec
  description: API specification for RPC services available at the nuts-network
  version: 0.1.0
  license:
    name: GPLv3
servers:
  - url: http://localhost:1323
paths:
  /internal/network/v1/transaction:
    get:
      summary: "Lists the transactions on the DAG"
      description: >
        Lists all transactions on the DAG. Since this call returns all transactions on the DAG, care should be taken when there
        are many of them.
        TODO: By then we'd need a more elaborate querying interface (ranging over timestamps/hashes, pagination, filtering, etc).

        error returns:
        * 500 - internal server error
      operationId: "listTransactions"
      tags:
        - transactions
      responses:
        "200":
          description: "Successfully listed the transactions"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        default:
          $ref: '../common/error_response.yaml'
  /internal/network/v1/transaction/{ref}:
    parameters:
      - name: ref
        in: path
        description: "Reference of the transaction"
        required: true
        example: "4960afbdf21280ef248081e6e52317735bbb929a204351291b773c252afeebf4"
        schema:
          type: string
    get:
      summary: "Retrieves a transaction"
      description: |
        Retrieves a transaction.

        error returns:
        * 400 - invalid transaction reference
        * 404 - transaction not found
        * 500 - internal server error
      operationId: "getTransaction"
      tags:
        - transactions
      responses:
        "200":
          description: "Transaction is known in the transaction log"
          content:
            application/jose:
              schema:
                type: string
        default:
          $ref: '../common/error_response.yaml'
  /internal/network/v1/transaction/{ref}/payload:
    parameters:
      - name: ref
        in: path
        description: "Reference of the transaction"
        required: true
        example: "4960afbdf21280ef248081e6e52317735bbb929a204351291b773c252afeebf4"
        schema:
          type: string
    get:
      summary: "Gets the transaction payload"
      operationId: "getTransactionPayload"
      description: |
        Gets the transaction payload.

        error returns:
        * 400 - invalid transaction reference
        * 404 - transaction or payload not found
        * 500 - internal server error
      tags:
        - transactions
      responses:
        "200":
          description: "Transaction found (with payload) and returned."
          content:
            application/octet-stream:
              example:
        default:
          $ref: '../common/error_response.yaml'
  /internal/network/v1/diagnostics/peers:
    get:
      summary: "Gets diagnostic information about the node's peers"
      operationId: "getPeerDiagnostics"
      tags:
        - diagnostics
      responses:
        "200":
          description: "Successfully retrieved peers diagnostics"
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/PeerDiagnostics'
        default:
          $ref: '../common/error_response.yaml'
  /internal/network/v1/diagnostics/graph:
    get:
      summary: "Visualizes the DAG as a graph"
      description: >
        Walks the DAG as subscribers of the DAG do, rendering it as graph. By default it renders in Graphviz format,
        which can be rendered to an image using `dot`.

        error returns:
        * 500 - internal server error
      operationId: "renderGraph"
      tags:
        - diagnostics
      responses:
        "200":
          description: "Graph successfully rendered"
          content:
            text/vnd.graphviz:
              schema:
                type: string
        default:
          $ref: '../common/error_response.yaml'
  /internal/network/v1/reprocess:
    post:
      summary: "Reprocess all transactions of the given type, verify and process"
      description: >
        Walks the DAG as subscribers do, only selects TXs of the given type are considered.
        The supported type values correspond with the transaction content-types.
        Transactions are not verified and added to an in-memory queue. For large sets of transactions, memory usage can become high.
        The API returns immediately.
        
        error returns:
        * 400 - missing type
      parameters:
        - name: type
          in: query
          description: the transaction content-type that must be reprocessed
          schema:
            type: string
          example: application/did+json
      operationId: reprocess
      tags:
        - admin
      responses:
        "202":
          description: "The request was accepted, process was started"
components:
  schemas:
    PeerDiagnostics:
      type: object
      description: Diagnostic information of a peer.
      properties:
        peers:
          description: IDs of the peer's peers.
          type: array
          items:
            type: string
        uptime:
          description: Number of seconds since the node started.
          type: number
        transactionNum:
          description: Number of transactions on the peer's DAG.
          type: number
        softwareID:
          description: >
            Identification of the particular Nuts implementation of the node.
            For open source implementations it's recommended to specify URL to the public, open source repository.
            Proprietary implementations could specify the product or vendor's name.
          type: string
        softwareVersion:
          description: Indication of the software version of the node. It's recommended to use a (Git) commit ID that uniquely resolves to a code revision, alternatively a semantic version could be used (e.g. 1.2.5).
          type: string
