package: v1
generate:
  echo-server: true
  client: true
  models: true
  strict-server: true
output-options:
  exclude-schemas:
  - ContactInformation
  - OrganizationSearchResult
  - Endpoint
  - CompoundService
