// Code generated by MockGen. DO NOT EDIT.
// Source: pki/pki.go

// Package pki is a generated GoMock package.
package pki

import (
	tls "crypto/tls"
	x509 "crypto/x509"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// AddCerts mocks base method.
func (m *MockValidator) AddCerts(cert []*x509.Certificate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCerts", cert)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCerts indicates an expected call of AddCerts.
func (mr *MockValidatorMockRecorder) AddCerts(cert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCerts", reflect.TypeOf((*MockValidator)(nil).AddCerts), cert)
}

// SetValidatePeerCertificateFunc mocks base method.
func (m *MockValidator) SetValidatePeerCertificateFunc(config *tls.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValidatePeerCertificateFunc", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValidatePeerCertificateFunc indicates an expected call of SetValidatePeerCertificateFunc.
func (mr *MockValidatorMockRecorder) SetValidatePeerCertificateFunc(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValidatePeerCertificateFunc", reflect.TypeOf((*MockValidator)(nil).SetValidatePeerCertificateFunc), config)
}

// Validate mocks base method.
func (m *MockValidator) Validate(chain []*x509.Certificate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", chain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate(chain interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate), chain)
}
