services:
  nodeA:
    image: "${IMAGE_NODE_A:-nutsfoundation/nuts-node:master}"
    ports:
      - "18081:8081"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often