openapi: "3.0.0"
info:
  title: Nuts registry API spec
  description: API specification for RPC services available at the nuts-registry
  version: 1.0.0
  license:
    name: GPLv3
paths:
  /internal/registry/v1/did:
    post:
      summary: "Creates a new Nuts DID"
      operationId: "createDID"
      tags:
        - DID
      responses:
        "201":
          description: "New DID has been created successfully. Returns the DID Document."
          content:
            application/json+did-document:
              schema:
                $ref: '#/components/schemas/DIDDocument'
        "500":
          description: "An error occurred while processing the request."
          content:
            text/plain:
              schema:
                type: string
    get:
      summary: "Searches for Nuts DIDs"
      operationId: searchDID
      tags:
        - DID
      parameters:
        - name: tags
          in: query
          description: "URL encoded DID or tag. When given a tag it must resolve to exactly one DID."
          required: true
          example:
            - "did:nuts:1234"
            - "tag:client-987731"
          schema:
            type: string
      responses:
        "200":
          description: "Search successful, response contains the DIDs"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "500":
          description: "An error occurred while processing the request."
          content:
            text/plain:
              schema:
                type: string
  /internal/registry/v1/did/{didOrTag}:
    parameters:
      - name: didOrTag
        in: path
        description: "URL encoded DID or tag. When given a tag it must resolve to exactly one DID."
        required: true
        example:
          - "did:nuts:1234"
          - "tag:client-987731"
        schema:
          type: string
    get:
      summary: "Resolves a Nuts DID Document"
      operationId: "getDID"
      tags:
        - DID
      responses:
        "200":
          description: "DID has been found and returned."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DIDResolutionResult"
        "404":
          description: "DID couldn't be found."
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: "An error occurred while processing the request."
          content:
            text/plain:
              schema:
                type: string
    put:
      summary: "Updates a Nuts DID Document"
      operationId: "updateDID"
      tags:
        - DID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                document:
                  $ref: "#/components/schemas/DIDDocument"
                currentHash:
                  description: "SHA-256 hash of the last version of the DID Document"
                  type: string
      responses:
        "200":
          description: "DID Document has been updated."
          content:
            application/json+did-document:
              schema:
                 $ref: '#/components/schemas/DIDDocument'
        "400":
          description: "DID couldn't be updated because the input conflicts."
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: "DID couldn't be found."
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: "An error occurred while processing the request."
          content:
            text/plain:
              schema:
                type: string
  /internal/registry/v1/did/{didOrTag}/tag:
    parameters:
      - name: didOrTag
        in: path
        description: "URL encoded DID or tag. When given a tag it must resolve to exactly one DID."
        required: true
        example:
          - "did:nuts:1234"
          - "tag:client-987731"
        schema:
          type: string
    post:
      summary: "Replaces the tags of the DID Document."
      operationId: updateDIDTags
      requestBody:
        description: "The new set of tags for the DID Document."
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        "204":
          description: "DID Document tags have been updated."
        "404":
          description: "DID couldn't be found."
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: "An error occurred while processing the request."
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    DIDDocument:
      type: object
      description: The actual DID Document in JSON representation.
    DIDDocumentMetadata:
      properties:
        created:
          description: "Date/time at which the document was originally created."
          type: string
          format: date-time
        updated:
          description: "Date/time at which the document (or this version) was updated."
          type: string
          format: date-time
        version:
          description: "Semantic version of the DID document."
          type: integer
        originJwsHash:
          description: "Hash (SHA-256, hex-encoded) of the JWS envelope of the first version of the DID document."
          type: string
        hash:
          description: "Hash (SHA-256, hex-encoded) of DID document bytes. Is equal to payloadHash in network layer."
          type: string
    DIDResolutionResult:
      properties:
        document:
          $ref: "#/components/schemas/DIDDocument"
        documentMetadata:
          $ref: '#/components/schemas/DIDDocumentMetadata'
        resolutionMetadata:
          type: object
          description: Metadata collected during DID Document (a.k.a. DID Resolution Metadata).