### Send POST request with json body
POST localhost:1323/internal/vcr/v2/issuer/vc
Content-Type: application/json

{
    "type": "NutsEmployeeCredential",
    "issuer": "did:nuts:8NYzfsndZJHh6GqzKiSBpyERrFxuX64z6tE5raa7nEjm",
    "credentialSubject": {
        "type": "Organization",
        "id": "did:nuts:8NYzfsndZJHh6GqzKiSBpyERrFxuX64z6tE5raa7nEjm",
        "member": {
          "identifier": "user@example.com",
          "type": "EmployeeRole",
          "roleName": "Verpleegkundige niveau 2",
          "member": {
            "type": "Person",
            "initials": "T",
            "familyName": "Tester"
          }
        }
    },
    "publishToNetwork": false
}