services:
  nodeA-backend:
    depends_on:
      db:
        condition: service_healthy
    environment:
      NUTS_STORAGE_SQL_CONNECTION: mysql://root:root@tcp(db:3306)/node_a?charset=utf8mb4&parseTime=True&loc=Local
  nodeB-backend:
    depends_on:
      db:
        condition: service_healthy
    environment:
      NUTS_STORAGE_SQL_CONNECTION: mysql://root:root@tcp(db:3306)/node_b?charset=utf8mb4&parseTime=True&loc=Local
  db:
    image: mysql:8.3.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      interval: 1s
      timeout: 5s
      retries: 20