services:
  nodeA-backend:
    depends_on:
      db:
        condition: service_healthy
    environment:
      NUTS_STORAGE_SQL_CONNECTION: sqlserver://sa:MyStrong(!)Password@db:1433?database=node_a
  nodeB-backend:
    depends_on:
      db:
        condition: service_healthy
    environment:
      NUTS_STORAGE_SQL_CONNECTION: sqlserver://sa:MyStrong(!)Password@db:1433?database=node_b
  db:
    # image: mcr.microsoft.com/azure-sql-edge:latest <-- "The sqlcmd utility is not included in the ARM64 version of the SQL Edge container" - https://github.com/microsoft/mssql-docker/issues/734
#    image: mcr.microsoft.com/mssql/server:2022-latest # <-- They broke the sqlcmd path - https://github.com/microsoft/mssql-docker/issues/892
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_USER: SA
      MSSQL_SA_PASSWORD: MyStrong(!)Password
      ACCEPT_EULA: Y
    volumes:
      - "./sqlserver.conf:/var/opt/mssql/mssql.conf"
      - "./sqlserver.key:/etc/ssl/mssql.key:ro"
      - "./sqlserver.pem:/etc/ssl/certs/mssql.pem:ro"
    healthcheck:
      test:
        ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "MyStrong(!)Password", "-Q", "SELECT 1"]
      interval: 2s
      timeout: 5s
      retries: 10
