@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(network, "Network Module", "Entry point for module")
Component(networkManager, "NetworkManager", "Orchestrates connections to peers, determines network layout")
Component(config, "Config")
Component(protocol, "Protocol", "Protocol implementation (v1, v2)")

Rel(network, networkManager, "Instantiates")
Rel(network, protocol, "Instantiates")
Rel(config, networkManager, "Configures")


@enduml