@startuml
participant "Network\n<size:10><i>Engine implementation" as Network
participant "ConnectionManager\n<size:10><i>Responsible for network topology" as ConnectionManager
participant "ManagedConnection\n<size:10><i>Maintains connections</i></size>" as ManagedConnection
participant "Protocol\n<size:10><i>Implements specific version, e.g. v1 or v2</i></size>" as Protocol

== Incoming Connection ==

]-> Protocol : Connect()
Protocol -> Protocol : readHeaders() : clientVersions, peerID
Protocol -> ConnectionManager : register(peerID, protocolVersion)
note right : Might be called multiple times\n (e.g. for both v1 and v2)

== Outgoing Connection ==

Network -> ConnectionManager : Connect(DID,\n grpcAddress)
note right: Might be fed by VDR subscription or\n bootstrap nodes read from config.
loop each protocol until every capability is supported, descending order
ManagedConnection -> Protocol : Connect(DID, grpcAddress)
Protocol -> ConnectionManager : register(peerID, protocolVersion)
end loop

== Invoking Capability ==

Network -> ConnectionManager : Invoke(receiverDID,\n capability, payload)
note right : Invocations will probably be\n read from a queue, e.g.\n private credentials or messages.\n If they fail they can be retried.\n Or they might be triggered by\n a process inside the protocol.
ConnectionManager -> ConnectionManager : findInvoker(peerID,\n capability) : invoker
ConnectionManager -> Protocol : invoke(payload)
]<- Protocol : send message
@enduml