services:
  nodeA-backend:
    image: "${IMAGE_NODE_A:-nutsfoundation/nuts-node:master}"
    ports:
      - "18081:8081"
    environment:
      NUTS_URL: "https://nodeA"
      NUTS_VERBOSITY: debug
      NUTS_STRICTMODE: false
      NUTS_HTTP_INTERNAL_ADDRESS: ":8081"
      NUTS_AUTH_CONTRACTVALIDATORS: dummy
      NUTS_POLICY_DIRECTORY: /opt/nuts/policies
      NUTS_DISCOVERY_DEFINITIONS_DIRECTORY: /nuts/discovery
      NUTS_DISCOVERY_SERVER_IDS: e2e-test
      NUTS_VDR_DIDMETHODS: web
    volumes:
      # did:web resolver uses the OS CA bundle, but e2e tests use a self-signed CA which can be found in truststore.pem
      # So we need to mount that file to the OS CA bundle location, otherwise did:web resolving will fail due to untrusted certs.
      - "../../tls-certs/truststore.pem:/etc/ssl/certs/Nuts_RootCA.pem:ro"
      - "./accesspolicy.json:/opt/nuts/policies/accesspolicy.json:ro"
      - "./discovery.json:/nuts/discovery/e2e-test.json:ro"
    healthcheck:
      interval: 1s # Make test run quicker by checking health status more often
  nodeA:
    image: nginx:1.25.1
    ports:
      - "10443:443"
    volumes:
      - "../../shared_config/nodeA-http-nginx.conf:/etc/nginx/conf.d/nuts-http.conf:ro"
      - "../../tls-certs/nodeA-certificate.pem:/etc/nginx/ssl/server.pem:ro"
      - "../../tls-certs/nodeA-certificate.pem:/etc/nginx/ssl/key.pem:ro"
      - "../../tls-certs/truststore.pem:/etc/nginx/ssl/truststore.pem:ro"
