apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: nuts-config
          configMap:
            name: nuts-config
        - name: nuts-ssl-secret
          secret:
            secretName: nuts-ssl-secret
        - name: nuts-data-pv
          persistentVolumeClaim:
            claimName: nuts-data-pvc
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NUTS_CONFIGFILE
              value: "/opt/nuts/nuts.yaml"
          volumeMounts:
            - name: nuts-config
              mountPath: /opt/nuts/nuts.yaml
              subPath: nuts.yaml
              readOnly: true
            - name: nuts-ssl-secret
              mountPath: /opt/nuts/ssl
              readOnly: true
            - name: nuts-data-pv
              mountPath: /opt/nuts/data
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort | default 1323 }}
              protocol: TCP
            - name: grpc
              containerPort: {{ template "grpcPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
