url: https://nodeA
strictmode: false
verbosity: debug
http:
  log: metadata-and-body
  internal:
    address: :8081
auth:
  contractvalidators:
    - dummy
  authorizationendpoint:
    enabled: true
policy:
  directory: /opt/nuts/policy
vdr:
  didmethods:
      - web