#
# Issue NutsAuthorizationCredential to a (local) care organization, which then happens over OIDC4VCI
#

### Create issuer DID document

POST http://localhost:1323/internal/vdr/v1/did
Content-Type: application/json

> {%
    client.global.set('issuer_did', response.body.id)
%}

### Create receiver DID document

POST http://localhost:1323/internal/vdr/v1/did
Content-Type: application/json

> {%
    client.global.set('receiver_did', response.body.id)
%}

### Register receiver's OIDC4VCI Client Metadata Endpoint

POST http://localhost:1323/internal/didman/v1/did/{{receiver_did}}/endpoint
Content-Type: application/json

{
  "type": "oidc4vci-wallet-metadata",
  "endpoint": "http://localhost:1323/identity/{{receiver_did}}/openid-credential-wallet-metadata"
}

### Issue VC (hopefully over OIDC4VCI, check logs)

POST http://localhost:1323/internal/vcr/v2/issuer/vc
Content-Type: application/json


{
  "type": "NutsAuthorizationCredential",
  "issuer": "{{issuer_did}}",
  "credentialSubject": {
    "id": "{{receiver_did}}",
    "resources": [],
    "purposeOfUse": "example",
    "subject": "urn:oid:2.16.840.1.113883.2.4.6.3:123456780"
  },
  "visibility": "private",
  "publish": true
}