@startuml
'https://plantuml.com/sequence-diagram

title Credential Offer (pre-authorized_code flow)

autonumber

box Credential Issuer
    participant Issuer
    participant OIDC4VCIIssuer as "OIDC4VCI\nIssuer"
    participant HolderClient as "Holder\nClient"
    participant IssuerAPI as "OIDC4VCI\nAPI"
end box

box Holder
    participant HolderAPI as "OIDC4VCI\nAPI"
    participant Wallet
    participant IssuerClient as "Issuer\nClient"
end box

group Credential Offer
    ' Issuer
    activate Issuer
    Issuer->Issuer : Lookup holder\nmdURL
    Issuer->OIDC4VCIIssuer ++ : Offer(credential, mdURL)
    OIDC4VCIIssuer->OIDC4VCIIssuer ++ : Create session\n(credential)
    OIDC4VCIIssuer-->OIDC4VCIIssuer -- : preAuthCode
    OIDC4VCIIssuer->OIDC4VCIIssuer ++ : Create offer\n(credential, preAuthCode)
    OIDC4VCIIssuer-->OIDC4VCIIssuer -- : offer
    OIDC4VCIIssuer->HolderClient **: Create\n(mdURL)
    HolderClient->HolderClient ++ : Load md
    HolderClient->HolderAPI ++: HTTP GET mdURL

    ' Holder
    HolderAPI->Wallet ++ : Get metadata\n(DID)
    Wallet-->HolderAPI -- : clientMD
    HolderAPI-->HolderClient --: clientMD

    ' Issuer
    HolderClient-->OIDC4VCIIssuer --
    OIDC4VCIIssuer->HolderClient ++ : OfferCredential\n(offer)
    HolderClient->HolderAPI ++ : HTTP POST\nto clientMD\nOfferEndpoint\n(offer)

    ' Holder
    HolderAPI -> Wallet ++ : AcceptCredentialOffer\n(offer)
    Wallet -> IssuerClient ** : Create\n(issuer)
    IssuerClient -> IssuerClient ++ : Load md\n(issuer/well-known)
    IssuerClient -> IssuerAPI ++ : HTTP GET\nmetadataURL
    IssuerAPI --> IssuerClient -- : issuerMD
    IssuerClient --> Wallet --
    note left
        Access token flow starts here
    end note
    HolderAPI --> HolderClient -- : 202 Accepted

    ' Issuer
    HolderClient-->OIDC4VCIIssuer --
    OIDC4VCIIssuer-->Issuer
    deactivate Issuer
    deactivate OIDC4VCIIssuer
end
@enduml