@startuml
'https://plantuml.com/sequence-diagram

title Credential Offer (pre-authorized_code flow)

autonumber

box Issuer
    participant Publisher as "OIDC4VCI\nPublisher"
    participant Issuer
    participant HolderClient as "Holder\nClient"
    participant IssuerAPI as "API"
end box

box Holder
    participant HolderAPI as "API"
    participant Wallet
    participant IssuerClient as "Issuer\nClient"
end box

group Credential Offer
    ' Issuer
    activate Publisher
    Publisher->Publisher : Lookup holder\nmdURL
    Publisher->Issuer ++ : Offer(credential, mdURL)
    Issuer->Issuer ++ : Create session\n(credential)
    Issuer-->Issuer -- : preAuthCode
    Issuer->Issuer ++ : Create offer\n(credential, preAuthCode)
    Issuer-->Issuer -- : offer
    Issuer->HolderClient **: Create\n(mdURL)
    HolderClient->HolderClient ++ : Load md
    HolderClient->HolderAPI ++: HTTP GET mdURL

    ' Holder
    HolderAPI->Wallet ++ : Get metadata\n(DID)
    Wallet-->HolderAPI -- : clientMD
    HolderAPI-->HolderClient --: clientMD

    ' Issuer
    HolderClient-->Issuer --
    Issuer->HolderClient ++ : OfferCredential\n(offer)
    HolderClient->HolderAPI ++ : HTTP POST\nto clientMD\nOfferEndpoint\n(offer)

    ' Holder
    HolderAPI -> Wallet ++ : AcceptCredentialOffer\n(offer)
    Wallet -> IssuerClient ** : Create\n(issuer)
    IssuerClient -> IssuerClient ++ : Load md\n(issuer/well-known)
    IssuerClient -> IssuerAPI ++ : HTTP GET\nmetadataURL
    IssuerAPI --> IssuerClient -- : issuerMD
    IssuerClient --> Wallet --
    note left
        Access token flow starts here
    end note
    HolderAPI --> HolderClient -- : 202 Accepted

    ' Issuer
    HolderClient-->Issuer --
    Issuer-->Publisher
    deactivate Publisher
    deactivate Issuer
end
@enduml