concept: organization
credentialType: NutsOrganizationCredential
indices:
  - name: index_id
    parts:
      - path: id
  - name: index_issuer
    parts:
      - path: issuer
  - name: index_subject
    parts:
      - path: credentialSubject.id
        alias: subject
  - name: index_name_city
    parts:
      - path: credentialSubject.organization.name
        alias: organization.name
        tokenizer: whitespace
        transformer: cologne
      - path: credentialSubject.organization.city
        alias: organization.city
        tokenizer: whitespace
        transformer: cologne
template: |
    {
      "id": "<<id>>",
      "issuer": "<<issuer>>",
      "type": "NutsOrganizationCredential",
      "subject": "<<credentialSubject.id>>",
      "organization": {
        "name": "<<credentialSubject.organization.name>>",
        "city": "<<credentialSubject.organization.city>>"
      }
    }
